POST http://localhost:8080/clientes
Content-Type: application/json

{
  "nombre": "Carlos",
  "primerApellido": "Otro",
  "segundoApellido": "Usuario",
  "email": "nuevo@gmail.com",
  "telefono": "3119876543",
  "contrasena": "654321",
  "salario": 4000000,
  "presupuesto": 200000000,
  "departamento": "QUINDIO",
  "municipio": {
    "nombre": "Armenia",
    "departamento": "QUINDIO"
  }
}